version: "3.9"

services:
  postgres:
    image: postgres:latest 
    volumes:
      - ./django-postgres/pysitee:/app/pysite
    env_file:
      - env
    environment:
      COMPOSE_HTTP_TIMEOUT: 3600
      POSTGRES_DB: postgres
      POSTGRES_USER: alen
      POSTGRES_PASSWORD: alen2007!
    ports:
      - "5432:5432"
    networks:
      - pgnet

  web:
    image: api:latest
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      DEPLOYMENT: api
      COMPOSE_HTTP_TIMEOUT: 3600
      LC_CTYPE: en_US.UTF-8
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
      POSTGRES_DB: postgres  # Example of environment variable used in Django, if applicable
    depends_on:
      - postgres
    stdin_open: true
    tty: true
    env_file: env
    command: bash -c "python3 pysitee/manage.py makemigrations && python3  pysitee/manage.py migrate && python3  pysitee/manage.py runserver 0.0.0.0:8000"

    networks:
      - pgnet

volumes:
  pgdata:
  esdata1:
    driver: local

networks:
  pgnet:
